apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 753397112861.dkr.ecr.us-east-1.amazonaws.com/frontend:bb61ea9e5c863fbb9e76e51b68f0f98c92796768
          ports:
            - containerPort: 80