apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: devops-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 753397112861.dkr.ecr.us-east-1.amazonaws.com/frontend:89e1163554cbeefd54fcd91101e00eafa2002ef7
          ports:
            - containerPort: 80