apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devops-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 753397112861.dkr.ecr.us-east-1.amazonaws.com/product-service:89e1163554cbeefd54fcd91101e00eafa2002ef7
          ports:
            - containerPort: 5000