name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Product Service
        run: |
          cd Services/product-service
          pip install -r requirements.txt
          python -m py_compile app.py

      - name: Test Cart Service
        run: |
          cd Services/cart-service
          pip install -r requirements.txt
          python -m py_compile app.py

      - name: Build Product Docker Image
        run: |
          docker build -t product-service ./Services/product-service

      - name: Build Cart Docker Image
        run: |
          docker build -t cart-service ./Services/cart-service

      - name: Build Frontend Docker Image
        run: |
          docker build -t frontend ./frontend